### ISSUE TITLE
GitHub Workflow and Quality Policy Docs

### ISSUE THREAD

**Issue by stucamp** [ASU-CodeDevils/flameboi-slack-api#20]
Define a standardized workflow, how to contribute, PR formatting/commentation, commit formatting/commentaion, etc.

**Comment by bananabrann** [comment]
You da man Stan!

**Comment by bananabrann** [comment]
I propose:

# Git Workflow
- Checkout branches is allowed (opposed to forking).
- Individual branch checkouts must start with their name. E.g., `brannan-dev` or `stu-dev`.
- `master` branch will **always** be the deployed version of the app, no buts.
- `dev` branch will be where we push approved merges to.
- Pushes from `dev` to `master` are only done by @stucamp and @KevinThePepper  and **only** when the the bot is updated on AWS, Slack, or any other platform.

In essence, the master branch will **always** be the current deployed bot. When master is updated, the bot is updated. All normal development branches (what we're doing right now with master) will be sent to dev.

# Contributing.md
- README references it.
- It will outline this git flow.
- Brief snippet of `git checkout -B <new-branch>`, `git pull origin/dev`, and `git push -u origin master`
- Outline any formatting stuff.

-------------

Thoughts?

**Comment by stucamp** [comment]
I like it!!!

**Comment by bananabrann** [comment]
Cool! I'll draft something up tomorrow and PR it for review

**Comment by KevinThePepper** [comment]
I like it, and may want to steal this for all CD projects as a standardized contribution/security policy. One thing I'd like to note is that there's branch protection on all branches with `master` and `dev` in the name, which means all named-dev branches would be merge-protected. This isn't a big deal, but just something to note.

Also maybe note that with this branch protection comes the requirement of 2 reviewers before merging, so maybe clarify that merges to `dev` or `master` must be approved by Stu and myself.

Past those, looks good!

**Comment by bananabrann** [comment]
Noted @KevinThePepper 

Will throw that in, thanks!

**Comment by stucamp** [comment]
that said studev is not... so think it'll only protect if it's a '-dev'

**Comment by bananabrann** [comment]
Right, only two protected branches under my intent is master and dev, with dev being default for merges and master for production.

I tested if "-dev" was a reserved word by adding a file in pierson-merge-test and merging it with pierson-dev. It merged successfully, not protected.
```
pi@pop-os:~/Developer/CodeDevils/flameboi-slack-api$ git merge pierson-merge-test
Updating 431e61b..1f7ff8d
Fast-forward
 Test-Merge.txt | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 Test-Merge.txt
pi@pop-os:~/Developer/CodeDevils/flameboi-slack-api$ 
```
